# Generated by Django 6.0.4 on 2026-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate'), ('HIRING_MANAGER', 'Hiring Manager')], default='CANDIDATE', max_length=20),
        ),
    ]
